---

language: python

python:
  - "2.7"

# Use the new container infrastructure
sudo: required

services:
  - docker

before_install:
  # Build CentOS image to verify ansible role there
  - docker build --rm=true --tag=el-6 tests/centos-6
  - docker build --rm=true --tag=el-7 tests/centos-7
  # Generate SSH key pair to test ansible role through SSH
  #- mkdir ${PWD}/.ssh && ssh-keygen -b 2048 -t rsa -f ${PWD}/.ssh/id_rsa -q -N ""

install:
  - pip install ansible && ansible --version
  # Rename a target directory
  - ln -sf -T $TRAVIS_BUILD_DIR $TRAVIS_BUILD_DIR/../grafana
  # Create ansible.cfg with correct roles_path
  - printf "[defaults]\nroles_path=$(dirname $TRAVIS_BUILD_DIR)\nhash_behaviour=merge" > ansible.cfg


script:
  # Add container name in inventory file and check syntax of the playbook
  - echo centos-6 >> tests/inventory
  - echo centos-7 >> tests/inventory
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check

  # Run container with SSH server
  - docker run -d --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --name centos-6 el-6
  - docker run -d --privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro --name centos-7 el-7

  # Run playbook
  - ansible-playbook tests/test.yml -i tests/inventory --sudo

  # Remove container
  - docker rm -f centos-6
  - docker rm -f centos-7

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/


