---

- name: deliver configuration
  template: src=grafana.ini.j2
            dest={{ grafana.service.conf }}/grafana.ini
            owner={{ grafana.service.owner }}
            group={{ grafana.service.owner }}
            mode=0640
  notify: restart grafana


- name: deliver ldap configuration
  template: src=ldap.toml.j2
            dest={{ grafana.service.conf }}/ldap.toml
            owner={{ grafana.service.owner }}
            group={{ grafana.service.owner }}
            mode=0640
  when: grafana.service.options.auth.ldap.enabled
  notify: restart grafana