---

- name: install packages
  package: name={{ grafana.providers.pkg.delim.join([item, grafana.service.version]) }}*
           update_cache=yes
           state=present
  with_items: "{{ grafana.providers.pkg.packages | select | list }}"

- name: create *.conf.d folder
  file: path={{ grafana.service.conf }} state=directory

- name: enable autostart on boot
  service: name={{ grafana.service.daemon }} enabled=yes
