---

- name: install packages
  package:
    name: "{{ item.1 }}"
    update_cache: yes
    state: present
    use: "{{ item.0 }}"
  loop: "{{ pm | zip(pm | map('extract', svc.providers, ['packages'])) | selectattr('1') | list }}"
  loop_control:
    label: "{{ item.0 }} -> {{ item.1 }}"
  vars:
    pm: "{{ svc.providers.keys() | list }}"

- name: create *.conf.d folder
  file:
    path: "{{ svc.service.conf }}"
    state: directory

- name: enable autostart on boot
  service:
    name: "{{ svc.service.daemon }}"
    enabled: yes
