---

- name: create OS-specific groups
  block:
    - name: group hosts by OS family
      group_by:
        key: "{{ ansible_os_family | lower }}"
      when: ansible_os_family is defined

    - name: group hosts by distribution
      group_by:
        key: "{{ ansible_os_family | lower }}{{ '%02d' | format(ansible_distribution_major_version | int) }}"
        parents:
          - "{{ ansible_os_family | lower }}"
      when:
        - ansible_os_family is defined
        - ansible_distribution_major_version is defined

    - name: include OS-specific settings
      include_vars:
        file: "{{ lookup('first_found', arguments, errors='ignore') }}"
        name: "_"
      vars:
        arguments:
          files: "{{ group_names | sort(reverse=True) | map('regex_replace', '^(.*)$', '\\1.yml') | list }}"
          paths: [ "vars" ]
  tags: always

- import_tasks: prepare.yml
  vars:
    svc: "{{ _.grafana | combine(grafana, recursive=True) }}"
  tags: [ prepare ]

- import_tasks: install.yml
  vars:
    svc: "{{ _.grafana | combine(grafana, recursive=True) }}"
  tags: [ install ]

- import_tasks: configure.yml
  vars:
    svc: "{{ _.grafana | combine(grafana, recursive=True) }}"
  tags: configure

- include: restart.yml
  tags: [start, restart]

# Verification tasks to make sure that the service is fine
#- include: verify.yml
#  tags: verify
