---

- name: add yum repositories
  yum_repository:
    name: "{{ item.key }}"
    description: "{{ item.value.description }}"
    file: "{{ item.key }}"
    baseurl: "{{ item.value.url }}"
    gpgkey: "{{ item.value['keys'] | join(' ') }}"
    gpgcheck: "{{ item.value.gpgcheck | default(true) }}"
    enabled: "{{ item.value.enabled | default(true) }}"
    repo_gpgcheck: "{{ item.value.repo_gpgcheck | default(omit) }}"
    sslverify: "{{ item.value.sslverify | default(omit) }}"
    sslcacert: "{{ item.value.sslcacert | default(omit) }}"
  loop: "{{ query('dict', svc.providers.yum.repositories | default({})) }}"
  no_log: yes